server:
  port: 8080
  servlet:
    context-path:
spring:
  datasource:
    username: root
    password: Umr_1123581321
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.117:3306/mp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true


logging:
  level:
    biz.lala.SpringBoot: debug
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
